version: '3.8'

services:
  brillante-php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}-php
    volumes:
      - .:/var/www
    networks:
      - brillante
    environment:
      PROJECT_NAME: ${PROJECT_NAME}

  brillante-nginx:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-nginx
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - brillante-php
    networks:
      - brillante
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=80"
      - "traefik.docker.network=app"

  brillante-db:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: aaa
    ports:
      - "3307:3306"
    labels:
      - traefik.enable=false
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - brillante

  brillante-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    environment:
      PMA_HOST: ${PROJECT_NAME}-db
      MYSQL_ROOT_PASSWORD: aaa
    depends_on:
      - ${PROJECT_NAME}-db
    networks:
      - brillante
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}-phpmyadmin.rule=Host(`${PHPMYADMIN_DOMAIN_NAME}`)"
      - "traefik.docker.network=app"

  brillante-vite:
    image: node:22
    container_name: ${PROJECT_NAME}-vite
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev"
    networks:
      - brillante
      - app
    ports:
      - "5173:5173" # Puerto por defecto de Vite
    labels:
      - traefik.enable=false

volumes:
  dbdata:

networks:
  app:
    external: true
  brillante:
    driver: bridge
